# Generated by Django 2.1.5 on 2019-01-21 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('songkick_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bandsintown_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(default='', max_length=255)),
                ('datetime', models.DateTimeField()),
                ('songkick_url', models.URLField(default='')),
                ('bandsintown_url', models.URLField(default='')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='venue.Venue')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
    ]
