# Generated by Django 2.1.5 on 2019-01-26 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('songkick_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(default='', max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
                ('songkick_url', models.URLField(default='')),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='venue.Venue')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='venue.Location')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
