# Generated by Django 2.1 on 2018-08-12 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songkick_id', models.PositiveIntegerField()),
                ('bandsintown_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('description', models.TextField()),
                ('songkick_url', models.URLField()),
                ('bandsintown_url', models.URLField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='venue.Venue')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
    ]
