# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='thumb_url',
            field=models.URLField(blank=True),
        ),
    ]
