# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20170725_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['datetime']},
        ),
    ]
