# Generated by Django 2.1 on 2018-08-04 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180804_2354'),
        ('event', '0004_auto_20170808_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='events',
        ),
    ]
