# Generated by Django 2.1 on 2018-08-04 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180805_0027'),
        ('event', '0005_auto_20180804_2354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='venue.Venue'),
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
