# Generated by Django 2.1.5 on 2019-02-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandsintown_id', models.IntegerField(null=True)),
                ('mbid', models.UUIDField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(default='https://s3.amazonaws.com/bit-photos/artistLarge.jpg')),
                ('thumb_url', models.URLField(default='https://s3.amazonaws.com/bit-photos/artistThumb.jpg')),
                ('songkick_url', models.URLField(default='')),
                ('bandsintown_url', models.URLField(default='')),
                ('facebook_page_url', models.URLField(default='')),
                ('events', models.ManyToManyField(related_name='artists', to='event.Event')),
                ('similar_artists', models.ManyToManyField(related_name='_artist_similar_artists_+', to='artist.Artist')),
            ],
        ),
    ]
