# Generated by Django 2.1 on 2018-08-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songkick_id', models.PositiveIntegerField()),
                ('bandsintown_id', models.PositiveIntegerField()),
                ('mbid', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('thumb_url', models.URLField()),
                ('facebook_url', models.URLField()),
                ('songkick_url', models.URLField()),
                ('bandsintown_url', models.URLField()),
                ('events', models.ManyToManyField(related_name='artists', to='event.Event')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
