# Generated by Django 2.1 on 2018-08-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('thumb_url', models.URLField(blank=True)),
                ('events', models.ManyToManyField(blank=True, related_name='artists', to='event.Event')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
