# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170805_1919'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='venues',
            field=models.ManyToManyField(blank=True, related_name='users', to='event.Venue'),
        ),
    ]
