# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_venues'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='thumb_url',
            field=models.URLField(blank=True),
        ),
    ]
