# Generated by Django 2.1 on 2018-08-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170904_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='users', to='artist.Artist'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='venues',
            field=models.ManyToManyField(blank=True, related_name='users', to='venue.Venue'),
        ),
    ]
