# Generated by Django 2.1 on 2018-08-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180804_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='users', to='artist.Artist'),
        ),
    ]
